### ISSUE TITLE
popen

### ISSUE THREAD

**Issue by sircobzac** [dudko/hfs#1]
how exactly hyts_std works, how it understands that it should use configuration files from out folder and  doesn't use default folder I:\hysplit4\working
maybe I don't fully understand popen and it tells hyts_std where to look for conf files.

**Comment by dudko** [comment]
Hi sircobzac,

sorry for my late replay. As far as I know, if you run `hyts_std.exe` without arguments it prompts you to enter all specifications for a single run. From your input is created the SETUP.CFG file used by `hyts_std.exe`. There are more configuration files that a necessary to have before a single run. You can find relevant information about them in the Advanced section of [HYSPLIT4 User's Guide](http://www.arl.noaa.gov/documents/reports/hysplit_user_guide.pdf).

From my scripts are generated just two configuration files: SETUP.CFG and ASCDATA.CFG. Before executing `hyts_std.exe`, with use of [Popen](https://docs.python.org/2/library/subprocess.html#subprocess.Popen), I just change the current working directory to the location with them. `hyts_std.exe` finds them automatically and starts the simulation.

**Comment by sircobzac** [comment]
Thank you very much! I didn't know that  hyts_std.exe finds configuration files automatically
 
Date: Tue, 4 Aug 2015 07:20:19 -0700
